---
title: "OPRA Compliance in New Jersey"
output: 
  flexdashboard::flex_dashboard:
    theme: default
    orientation: rows
    source_code: "https://github.com/gavinrozzi/nj-opra-dashboard"
    vertical_layout: fill
runtime: shiny

---
  
```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)
library(rjson)

knitr::opts_chunk$set(cache=FALSE)

# Read in geojson shapefile of NJ county boundaries
nj_counties <- rjson::fromJSON(file='data/County_Boundaries_of_NJ.geojson')

# Read in CSV file of OPRA request data
requests <- read.csv('data/output.csv')

# Request count by authority
authorities <- requests %>% count(vars = requested_from) %>% arrange(desc(n))

# Request count by user
users <- requests %>% count(vars = requested_by) %>% arrange(desc(n))

# Summaries by request state
request_counts <- requests %>% count(vars = described_state) %>% arrange(desc(n))

# Get average response time for authority TODO: move to processing script
#1. Get all requests for that authority
for (i in 1:nrow(authorities)) {
authority_requests <- requests %>% filter(`requested_from` == authorities$vars[i])
authorities$average_response_time[i] <- mean(na.omit(authority_requests$days_until_response))
}

# Get county summaries computed from county_summaries script
counties <- read_csv('data/county_summaries.csv')

```
Home
=====================================

About the Dashboard {.sidebar}
-----------------------------------------------------------------------
  
How well are government agencies complying with New Jersey's freedom of information law, the Open Public Records Act?

[OPRAmachine](https://opramachine.com/) has been tracking requests submitted by users since 2017. 
The data displayed in this dashboard was dervied from the website. 
This dashboard does not track all OPRA requests from New Jersey, only those that were submitted via OPRAmachine.


Column
-----------------------------------------------------------------------

### Total requests

```{r}
renderValueBox({
  total_requests <- nrow(requests)
  valueBox(total_requests , 
           icon = "fa-copy")
})
```

### Public authorities

```{r}
renderValueBox({
  total_auth <- nrow(authorities)
  valueBox(total_auth , 
           icon = "fa-university")
})
```

### OPRA requesters

```{r}
renderValueBox({
  total_users <- nrow(users)
  valueBox(total_users, 
           icon = "fa-user-edit")
})
```

### Average days until response

```{r}
renderValueBox({
  # Remove requests that failed to deliver from average response time calculation
  requests_error_omit <- requests %>% filter(described_state != 'error_message')
  avg_response <- round(mean(na.omit(requests_error_omit$days_until_response)), digits = 2)
  valueBox(avg_response, 
           icon = "fa-clock",
           color = ifelse(avg_response > 7, "warning", "primary"))
})
```


Column 
-----------------------------------------------------------------------

### Successful requests

```{r}
successful <- nrow(requests %>% filter(described_state == 'successful' | described_state == 'partially_successful'))
rate <- round(successful / nrow(requests) * 100, digits = 2)

gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Answered within 7 business days

```{r}
percent_within_7days <- round(nrow(requests %>% filter(days_until_response < 7)) / nrow(requests) * 100, digits = 2)

gauge(percent_within_7days, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


### Requests awaiting response

```{r}
awaiting_response <- nrow(requests %>% filter(described_state == 'waiting_response'))
rate <- round(awaiting_response / nrow(requests) * 100, digits = 2)

gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Requests awaiting classification

```{r}
awaiting_classification <- nrow(requests %>% filter(awaiting_description == 'TRUE'))
rate <- round(awaiting_classification / nrow(requests) * 100, digits = 2)

gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Unsuccessful requests

```{r}
unsuccessful <- nrow(requests %>% filter(described_state == 'rejected' | described_state == 'not_held'))
rate <- round(unsuccessful / nrow(requests) * 100, digits = 2)

gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

Column {data-height=850}
-----------------------------------------------------------------------
### Response times by county

```{r}
county_1 <- plot_ly() 
county_1 <- county_1 %>% add_trace(
  type="choroplethmapbox",
  geojson=nj_counties,
  locations=counties$fips_code,
  z=counties$average_response_time,
  featureidkey="properties.FIPSSTCO",
  colorscale="Viridis",
  zmin=0,
  zmax=20,
  marker=list(line=list(
    width=0),
    opacity=1.0
  )
)
county_1 <- county_1 %>% layout(margin = list(b = 50, l = 50),
                      mapbox=list(
                        style="carto-positron",
                        zoom = 6,
                        center=list(lon= -74.558333, lat=40.07))
)
county_1 <- county_1 %>% layout(title = 'Average OPRA response time by county, 2017-2020') %>% colorbar(title = "Days until response")
renderPlotly(county_1)

```

### Requests by county

```{r}
county_2 <- plot_ly() 
county_2 <- county_2 %>% add_trace(
  type="choroplethmapbox",
  geojson=nj_counties,
  locations=counties$fips_code,
  z=counties$total_requests,
  featureidkey="properties.FIPSSTCO",
  colorscale="Viridis",
  zmin=0,
  zmax=2500,
  marker=list(line=list(
    width=0),
    opacity=1.0
  )
)
county_2 <- county_2 %>% layout(margin = list(b = 50, l = 50),
                      mapbox=list(
                        style="carto-positron",
                        zoom = 6,
                        center=list(lon= -74.558333, lat=40.07))
)
county_2 <- county_2 %>% layout(title = 'Total OPRA requests by county, 2017-2020') %>% colorbar(title = "Number of requests")
renderPlotly(county_2)

```

Public Authority Statistics
=====================================

Column 
-----------------------------------------------------------------------

### Authorities with the most requests

```{r}
# Get top 10 authorities by request count
top10 <- authorities %>% top_n(10, wt=n) %>% arrange(desc(n))

# Make an ordered factor
top10$vars <- factor(top10$vars, levels = top10$vars)

# Plot them with Plotly
fig <- plot_ly(
  x = top10$vars,
  y = top10$n,
  name = "Requests by authority",
  type = "bar"
)
fig
  
```


### Request states on OPRAmachine

```{r}
# Get top 10 authorities TODO: replace this graph with a county choropleth
top10 <- authorities %>% top_n(10)
#top10 <- na.omit(top25[ -c(1) ])

# Make an ordered factor

# Plot them with Plotly
fig <- request_counts %>% plot_ly(labels=~vars, values=~n)
fig <- fig %>% add_pie(hole = 0.6)
fig
  
```


### Slowest to respond

```{r}
# Get top 10 slowest authorities
top10times <- authorities %>% top_n(10, wt=average_response_time) %>% arrange(desc(average_response_time))

# Make an ordered factor
top10times$vars <- factor(top10$vars, levels = top10$vars)

# Plot them with Plotly
fig <- plot_ly(
  x = top10times$vars,
  y = top10times$average_response_time,
  name = "Top 10 longest to respond",
  type = "bar",
)
fig
```


Row
-----------------------------------------------------------------------

By County
=====================================
  
  Compare by County {.sidebar}
-----------------------------------------------------------------------
  How do New Jersey's counties compare for OPRA response times?

```{r}
selectInput("county_name", "County Name", choices = counties$Name)

```

Row
-----------------------------------------------------------------------

### Average response time for this county


```{r}
renderValueBox({
  # Get tag for selected county
  county_tag <- paste0(input$county_name,'County')
  county_tag <- str_replace_all(string=county_tag, pattern=" ", repl="")
  # Filter requests containing the tag
  county_requests <- requests %>% filter(str_detect(tag1, county_tag) | str_detect(tag2, county_tag) |  str_detect(tag3, county_tag) | str_detect(tag4, county_tag)) %>% filter(described_state != 'error_message')
  # Calculate average response time for the county
  county_response_time <- round(mean(na.omit(county_requests$days_until_response)),digits = 2)
  
  # Remove requests that failed to deliver from average response time calculation
  requests_error_omit <- requests %>% filter(described_state != 'error_message')
  avg_response <- round(mean(na.omit(requests_error_omit$days_until_response)), digits = 2)
  
  valueBox(paste(county_response_time,'days'), 
           icon = "fa-clock",
           color = ifelse(avg_response > 7, "warning", "primary"))
  })

```

### Average response time for all counties


```{r}
renderValueBox({
  all_counties_response_time <- round(mean(counties$average_response_time), digits = 2)
  valueBox(paste(all_counties_response_time,'days'), 
           icon = "fa-clock",
           color = ifelse(all_counties_response_time > 7, "warning", "primary"))
  })

```

Row
-----------------------------------------------------------------------

```{r}
 renderUI(tags$h1(paste(input$county_name,'County at a glance')))

```

```{r}
renderUI({
county_tag <- paste0(input$county_name, 'County')

county_requests <- requests %>% filter(str_detect(tag1, county_tag) | str_detect(tag2, county_tag) |  str_detect(tag3, county_tag) | str_detect(tag4, county_tag)) %>% filter(described_state != 'error_message')

county_authorities <- county_requests %>% count(vars = requested_from) %>% arrange(desc(n))

# Get top 10 authorities by request count
top10 <- county_authorities %>% top_n(10, wt=n) %>% arrange(desc(n))

# Make an ordered factor
top10$vars <- factor(top10$vars, levels = top10$vars)

# Plot them with Plotly
fig <- plot_ly(
  x = top10$vars,
  y = top10$n,
  name = "Requests by authority",
  type = "bar"
)
fig
})
```



All requests 
=====================================

Row
-----------------------------------------------------------------------


### All OPRA requests
  
  ```{r}
DT::renderDataTable({
  DT::datatable(requests, extensions = 'Responsive', escape = FALSE, rownames = FALSE,
  options = list(
    bPaginate = TRUE
  ))
})
  ```

